$primary = rgb(2ec09c)
$surface = rgb(062329)
$secondary = rgb(8cde94)
$error = rgb(ff0000)
$tertiary = rgb(7ad0c6)
$surface_lowest = rgb(07262b)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
