# Source Files
source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/startup.conf
source = $HOME/.config/hypr/inputs.conf
source = $HOME/.config/hypr/keybinds.conf
source = $HOME/.config/hypr/windowrules.conf
source = $HOME/.config/hypr/animations.conf
source = $HOME/.config/hypr/themes/theme.conf

# Volume controls
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Brightness controls
bindel = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Layouts
# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/
dwindle {
    preserve_split = yes
}

scrolling {
    column_width = 0.5
    direction = right
    fullscreen_on_one_column = true
    focus_fit_method = 1
    follow_focus = true
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/
master {
    new_status = master
}


# Misc
# See https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    vrr = 0                      # 0=OFF 1=ON 2=FULLSCREEN ONLY
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    anr_missed_pings = 5
    allow_session_lock_restore = true
}

xwayland {
    force_zero_scaling = true
}

general {
    snap {                       # snapping for floating windows
        enabled = true
    }
}

source = $HOME/.config/hypr/noctalia/noctalia-colors.conf
