-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        rounding = 10,
    },
    general = {
        border_size = 2,
    },
})

-- Bezier curves
hl.curve("wind", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })

-- Animations
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.0,
    bezier = "wind",
    style = "popin",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 4.0,
    bezier = "wind",
    style = "popin",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 5.0,
    bezier = "wind",
    style = "slidevert",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 5.0,
    bezier = "wind",
    style = "slidevert",
})
